jobs:
  include:
  - stage: Build

    language: node_js
    sudo: required
    services:
    - docker
    node_js: 10
    script: |
      npm run build && \
      docker build -t ${DOCKER_USER}/montdenis .
    after_success: |
      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin && \
        docker push ${DOCKER_USER}/montdenis
      fi

  - stage: Deploy

    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: 'curl -H "Authorization: GitHub ${GITHUB_OAUTH_TOKEN}" -X POST https://dashboard-api.vibioh.fr/deploy/montdenis/ --data-binary @docker-compose.yml'

stages:
  - Build
  - name: Deploy
    if: branch = master

notifications:
  email: false
