---

jobs:
  include:
    - stage: Build

      language: node_js
      node_js:
        - 13
      script: npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GITHUB_TOKEN}
        local_dir: dist/
        on:
          branch: master

stages:
  - Build

notifications:
  email: false
