---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pension
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: app
      version: "0.0.20"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 10m

  values:
    nameOverride: pension

    image:
      repository: vibioh/montdenis

    config:
      VIWS_LOGGER_JSON: "true"

    ingress:
      enabled: true
      hosts:
        - pension.montdenis.fr
