apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pension
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.68"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: pension
    image:
      name: vibioh/montdenis
      tag: "202105090623" # {"$imagepolicy": "default:flux-montdenis-web:tag"}
    config:
      VIWS_LOGGER_JSON: "true"
    ingress:
      enabled: true
      hosts:
      - pension.montdenis.fr
    canary:
      enabled: true
      url: https://pension.montdenis.fr
