apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pension
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.43'
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m
  values:
    nameOverride: pension
    image:
      repository: vibioh/montdenis:202102152201 # {"$imagepolicy": "default:site-montdenis"}
    config:
      VIWS_LOGGER_JSON: 'true'
    ingress:
      enabled: true
      hosts:
      - pension.montdenis.fr
