apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pension
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.46"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m
  install:
    skipCRDs: true
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: pension
    image:
      repository: vibioh/montdenis:202102280748 # {"$imagepolicy": "default:flux-montdenis-web"}
    config:
      VIWS_LOGGER_JSON: "true"
    ingress:
      enabled: true
      hosts:
      - pension.montdenis.fr
