---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pension
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pension
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
