apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pension
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.83"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: pension
    image:
      name: vibioh/montdenis
      tag: "202207130739" # {"$imagepolicy": "default:flux-montdenis-web:tag"}
    config:
      VIWS_LOGGER_JSON: "true"
      VIWS_PROMETHEUS_GZIP: "false"
      VIWS_GZIP: "false"
    ingress:
      enabled: true
      hosts:
        - pension.montdenis.fr
    pprof:
      enabled: true
